apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: poc
data:
  PORT: "3002"
  MONGODB_DB: inventory
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_ENDPOINT_URL: http://localstack:4566
  SQS_INVENTORY_QUEUE_URL: http://localstack:4566/000000000000/inventory-queue
