apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: poc
spec:
  clusterIP: None          # headless — direct pod DNS for StatefulSet
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
