apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: poc
data:
  PORT: "3001"
  MONGODB_DB: orders
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_ENDPOINT_URL: http://localstack:4566
  SNS_ORDER_EVENTS_ARN: arn:aws:sns:us-east-1:000000000000:order-events
