apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: poc
data:
  PORT: "3003"
  MONGODB_DB: notifications
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_ENDPOINT_URL: http://localstack:4566
  SQS_NOTIFICATION_QUEUE_URL: http://localstack:4566/000000000000/notification-queue
