apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poc-ingress
  namespace: poc
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    # Force HTTPS redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # cert-manager will provision the TLS certificate
    cert-manager.io/cluster-issuer: poc-ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - localhost
      secretName: poc-tls-secret
  rules:
    - host: localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bff
                port:
                  number: 3000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: bff
                port:
                  number: 3000
          - path: /ready
            pathType: Prefix
            backend:
              service:
                name: bff
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
